class ARGS: #Collect all ARGS of task (Transfer by Manager)
  MYSQL_DB = "tik_vn_nancy_1"
  USER_EMAIL = "tranhuudung1986@gmail.com"
  USER_PASS = "H@@n24687"
  DELAY = "0"
  READY_LIST_PATH = "/HShare/0_AllTasks/1_ready_list"
  CLIP_CAPTION = "❤ Nancy ❤ #nancy #momoland #gaixinh #xuhuong #foryou #fyp"
  CLIP_HASHTAG = ""
  CLIP_MODE = "PUBLIC"
  CHROME_PROFILE = "AUTOSEARCH"
