# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.tiktok.com/")
    # 2 | setWindowSize | 1888x1408 | 
    self.driver.set_window_size(1888, 1408)
    # 3 | assertTitle | TikTok - Make Your Day | 
    assert self.driver.title == "TikTok - Make Your Day"
    
    time.sleep(100000)
    # 4 | click | name=q | 
    self.driver.find_element(By.NAME, "q").click()
    # 5 | type | name=q | girlxinh
    self.driver.find_element(By.NAME, "q").send_keys("girlxinh")
    # 6 | click | css=.search-button-container | 
    self.driver.find_element(By.CSS_SELECTOR, ".search-button-container").click()
    # 7 | click | css=.tiktok-zbo8c5-ButtonMore | 
    self.driver.find_element(By.CSS_SELECTOR, ".tiktok-zbo8c5-ButtonMore").click()
    # 8 | click | css=.tiktok-zbo8c5-ButtonMore | 
    self.driver.find_element(By.CSS_SELECTOR, ".tiktok-zbo8c5-ButtonMore").click()
    # 9 | click | css=.tiktok-zbo8c5-ButtonMore | 
    self.driver.find_element(By.CSS_SELECTOR, ".tiktok-zbo8c5-ButtonMore").click()
    # 10 | click | css=.tiktok-zbo8c5-ButtonMore | 
    self.driver.find_element(By.CSS_SELECTOR, ".tiktok-zbo8c5-ButtonMore").click()
    # 11 | click | css=.tiktok-zbo8c5-ButtonMore | 
    self.driver.find_element(By.CSS_SELECTOR, ".tiktok-zbo8c5-ButtonMore").click()
  
